aqsol – filterSD
aqsol Subroutine
72 statements
Source File
subroutine aqsol(n, a, la, q, Q_, R, EB, z, t, u, x, d, ws, lr, lc, li, lv, le, pp, qq)
Arguments
Type Intent Optional Attributes Name
integer :: n
real :: a
integer :: la
real :: q
double precision :: Q_
real :: R
real :: EB
real :: z
real :: t
real :: u
real :: x
real :: d
real :: ws
integer :: lr
integer :: lc
integer :: li
integer :: lv
integer :: le
real :: pp
real :: qq
Calls
Called by
Contents
Common Blocks
factorc refactorc pqc
Common Blocks
common /factorc/
Type Attributes Name Initial
integer :: m1
integer :: m2
integer :: mp
integer :: mq
integer :: lastr
integer :: irow
common /refactorc/
Type Attributes Name Initial
integer :: mc
integer :: mxmc
common /pqc/
Type Attributes Name Initial
real :: pc
real :: qr
integer :: lmp
Call graph
aqsol calls qtprod, aqsol0, rsol, scpr, iscatter
qtprod calls scpr
aqsol0 calls scpr, iscatter
rsol calls scpr
updatese calls aqsol