check – filterSD
check Subroutine
116 statements
Source File
subroutine check(n, nm, nmi, kmax, g, a, la, x, bl, bu, r, ls, an, f, ws, lws, cws, ninf, peq, k, lev, p, alp2)
Arguments
Type Intent Optional Attributes Name
integer :: n
integer :: nm
integer :: nmi
integer :: kmax
real :: g
real :: a
integer :: la
real :: x
real :: bl
real :: bu
real :: r
integer :: ls
real :: an
real :: f
real :: ws
integer :: lws
character :: cws(*)
integer :: ninf
real :: peq
integer :: k
integer :: lev
real :: p
real :: alp2
Calls
Contents
Common Blocks
noutc epsc
Common Blocks
common /noutc/
Type Attributes Name Initial
integer :: nout
common /epsc/
Type Attributes Name Initial
real :: eps
real :: tol
real :: emin
Call graph
check calls aiscpr, scpr, grad, funct
funct calls aiscpr, scpr