eptsol – filterSD
eptsol Subroutine
80 statements
Source File
subroutine eptsol(n, a, la, p, b, Q_, R, EB, y, s, u, x, d, ws, lr, lc, li, lv, le, pp, qq, ep)
Arguments
Type Intent Optional Attributes Name
integer :: n
real :: a
integer :: la
real :: p
real :: b
double precision :: Q_
real :: R
real :: EB
real :: y
real :: s
real :: u
real :: x
real :: d
real :: ws
integer :: lr
integer :: lc
integer :: li
integer :: lv
integer :: le
real :: pp
real :: qq
real :: ep
Calls
Called by
Contents
Common Blocks
epsc factorc refactorc pqc
Common Blocks
common /epsc/
Type Attributes Name Initial
real :: eps
real :: tol
real :: emin
common /factorc/
Type Attributes Name Initial
integer :: m1
integer :: m2
integer :: mp
integer :: mq
integer :: lastr
integer :: irow
common /refactorc/
Type Attributes Name Initial
integer :: mc
integer :: mxmc
common /pqc/
Type Attributes Name Initial
real :: pc
real :: qr
integer :: lmp
Call graph
eptsol calls xlen, rtsol, eptsol0, aiscpri, qprod
eptsol0 calls aiscpri
updatese calls eptsol