factor – filterSD
factor Subroutine
185 statements
Source File
subroutine factor(n, nm, nu, nc, a, la, e, ls, sn, tn, un, xn, lr, lc, li, mao, p, q, r, s, ws, mxws, d, ifail)
Arguments
Type Intent Optional Attributes Name
integer :: n
integer :: nm
integer :: nu
integer :: nc
real :: a
integer :: la
real :: e
integer :: ls
real :: sn
real :: tn
real :: un
real :: xn
integer :: lr
integer :: lc
integer :: li
integer :: mao
real :: p
real :: q
integer :: r
integer :: s
real :: ws
integer :: mxws
real :: d
integer :: ifail
Calls
Contents
Common Blocks
factorc iprintc refactorc epsc noutc
Common Blocks
common /factorc/
Type Attributes Name Initial
integer :: m1
integer :: m2
integer :: mp
integer :: mq
integer :: lastr
integer :: irow
common /iprintc/
Type Attributes Name Initial
integer :: iprint
common /refactorc/
Type Attributes Name Initial
integer :: nup
integer :: nfreq
common /epsc/
Type Attributes Name Initial
real :: eps
real :: tol
real :: emin
common /noutc/
Type Attributes Name Initial
integer :: nout
Call graph
factor calls scpr, newslot, iscatter, aiscpri
newslot calls erase