filter_SD – filterSD
filter_SD Subroutine
557 statements
Source File
subroutine filter_SD(n, f, fmin, cstype, bl, bu, ws, lws, v, nv, maxa, kmax, maxg, d, dl, du, g, r, w, e, ls, alp, lp, filh, filf, rho, htol, rgtol, maxit, iprint, nout, ifail)
Arguments
Type Intent Optional Attributes Name
integer :: n
real :: f
real :: fmin
character :: cstype(*)
real :: bl
real :: bu
real :: ws
integer :: lws
real :: v
integer :: nv
integer :: maxa
integer :: kmax
integer :: maxg
real :: d
real :: dl
real :: du
real :: g
real :: r
real :: w
real :: e
integer :: ls
real :: alp
integer :: lp
real :: filh
real :: filf
real :: rho
real :: htol
real :: rgtol
integer :: maxit
integer :: iprint
integer :: nout
integer :: ifail
Calls
Contents
Common Blocks
defaultc epsc repc functc infoc ngrc statsc
Common Blocks
common /defaultc/
Type Attributes Name Initial
real :: ainfty
real :: ubd
integer :: mlp
integer :: mxf
common /epsc/
Type Attributes Name Initial
real :: eps
real :: tol
real :: emin
common /repc/
Type Attributes Name Initial
real :: sgnf
integer :: nrep
integer :: npiv
integer :: nres
common /functc/
Type Attributes Name Initial
real :: fxd
real :: alc
integer :: m
integer :: iph
integer :: last1
integer :: next1
integer :: nx
integer :: nx1
integer :: nal
integer :: nal1
integer :: naal
integer :: naal1
integer :: nxd
integer :: nxd1
integer :: ncx
integer :: ncx1
integer :: ncxd
integer :: ncxd1
integer :: nla1
common /infoc/
Type Attributes Name Initial
real :: rgnorm
real :: vstep
integer :: iter
integer :: npv
integer :: nfn
integer :: ngr
common /ngrc/
Type Attributes Name Initial
integer :: mxgr
common /statsc/
Type Attributes Name Initial
real :: dnorm
real :: h
real :: hJt
real :: hJ
integer :: ipeq
integer :: k
integer :: itn
integer :: nft
integer :: ngt
Call graph
filter_sd calls iexch, addfil, scpr, testfil