glcpd – filterSD
glcpd Subroutine
959 statements
Source File
subroutine glcpd(n, m, k, kmax, maxg, a, la, x, bl, bu, f, fmin, g, r, w, e, ls, alp, lp, mlp, peq, ws, lws, cws, v, nv, rgtol, m0de, ifail, mxgr, iprint, nout)
Arguments
Type Intent Optional Attributes Name
integer :: n
integer :: m
integer :: k
integer :: kmax
integer :: maxg
real :: a
integer :: la
real :: x
real :: bl
real :: bu
real :: f
real :: fmin
real :: g
real :: r
real :: w
real :: e
integer :: ls
real :: alp
integer :: lp
integer :: mlp
real :: peq
real :: ws
integer :: lws
character :: cws(*)
real :: v
integer :: nv
real :: rgtol
integer :: m0de
integer :: ifail
integer :: mxgr
integer :: iprint
integer :: nout
Calls
Contents
Common Blocks
lcpdc epsc infoc repc wsc refactorc alphac
Common Blocks
common /lcpdc/
Type Attributes Name Initial
integer :: na
integer :: na1
integer :: nb
integer :: nb1
integer :: krg
integer :: krg1
integer :: kr
integer :: kr1
integer :: ka
integer :: ka1
integer :: kb
integer :: kb1
integer :: kc
integer :: kc1
integer :: kd
integer :: kd1
integer :: ke
integer :: ke1
integer :: lu1
integer :: ll1
common /epsc/
Type Attributes Name Initial
real :: eps
real :: t0l
real :: emin
common /infoc/
Type Attributes Name Initial
real :: rgnorm
real :: vstep
integer :: iter
integer :: npv
integer :: nfn
integer :: ngr
common /repc/
Type Attributes Name Initial
real :: sgnf
integer :: nrep
integer :: npiv
integer :: nres
common /wsc/
Type Attributes Name Initial
integer :: kk
integer :: ll
integer :: kkk
integer :: lll
integer :: mxws
integer :: mxlws
common /refactorc/
Type Attributes Name Initial
integer :: mc
integer :: mxmc
common /alphac/
Type Attributes Name Initial
real :: alpha
real :: rp
real :: pj
real :: qqj
real :: qqj1
Call graph
glcpd calls optest, insort, 4, iexch, newg, signst, stmap, funct, grad, scpr
funct calls scpr, aiscpr