newg – filterSD
newg Subroutine
5 statements
Source File
subroutine newg()
Arguments
None
Called by
Contents
Common Blocks
factorc
Common Blocks
common /factorc/
Type Attributes Name Initial
integer :: m1
integer :: m2
integer :: mp
integer :: mq
integer :: lastr
integer :: irow
Call graph
glcpd calls newg
l1sold calls newg
qlcpd calls newg