newslot – filterSD
newslot Subroutine
83 statements
Source File
subroutine newslot(row, len, lastr, irow, p, q, r, s, ws, mxws, qr_, ifail)
Arguments
Type Intent Optional Attributes Name
real :: row
integer :: len
integer :: lastr
integer :: irow
real :: p
real :: q
real :: r
real :: s
real :: ws
integer :: mxws
real :: qr_
integer :: ifail
Calls
Called by
Contents
Common Blocks
noutc
Common Blocks
common /noutc/
Type Attributes Name Initial
integer :: nout
Call graph
newslot calls erase
factor calls newslot
re_factor calls newslot