scpr – filterSD
scpr Function
8 statements
Source File
function scpr(a, x, y, n)
Arguments
Type Intent Optional Attributes Name
real :: a
real :: x
real :: y
integer :: n
Return Value real
Called by
Contents
Source Code
scpr
Source Code
      function scpr(a,x,y,n)
      implicit double precision (a-h,o-z)
      dimension x(*),y(*)
      scpr=a
      do i=1,n
        scpr=scpr+x(i)*y(i)
      end do
      end function scpr
Call graph
formr calls scpr
funct calls scpr
rsol calls scpr
re_factor calls scpr
aqsol calls scpr, rsol, qtprod, aqsol0
glcpd calls scpr, funct
factor calls scpr
check calls scpr, funct
check1 calls scpr
filter_sd calls scpr
qtprod calls scpr
tfbsub calls scpr
l1sold calls scpr
aqsol0 calls scpr
updateqr calls scpr
pivot calls scpr
setfg2 calls scpr
aiscpr calls scpr
ailen calls scpr
checkq calls scpr, setfg2
qlcpd calls scpr, setfg2
updatese calls aqsol
checkg calls funct