setfg2 – filterSD
setfg2 Subroutine
22 statements
Source File
subroutine setfg2(n, linear, a, la, x, f, g, ws, lws)
Arguments
Type Intent Optional Attributes Name
integer :: n
logical :: linear
real :: a
integer :: la
real :: x
real :: f
real :: g
real :: ws
integer :: lws
Calls
Called by
Contents
Common Blocks
noutc
Common Blocks
common /noutc/
Type Attributes Name Initial
integer :: nout
Call graph
setfg2 calls gdotx, saipy, scpr, aiscpr
checkq calls setfg2
qlcpd calls setfg2