updateSE – filterSD
updateSE Subroutine
49 statements
Source File
subroutine updateSE(p, q, n, nm, a, la, e, Q_, R, EB, y, z, s, t, u, x, d, ws, lr, lc, li, pp, qq, lm, lv, le, ifail)
Arguments
Type Intent Optional Attributes Name
integer :: p
integer :: q
integer :: n
integer :: nm
real :: a
integer :: la
real :: e
real :: Q_
real :: R
real :: EB
real :: y
real :: z
real :: s
real :: t
real :: u
real :: x
real :: d
real :: ws
integer :: lr
integer :: lc
integer :: li
integer :: pp
integer :: qq
integer :: lm
integer :: lv
integer :: le
integer :: ifail
Calls
Contents
Common Blocks
factorc refactorc epsc pqc
Common Blocks
common /factorc/
Type Attributes Name Initial
integer :: m1
integer :: m2
integer :: mp
integer :: mq
integer :: lastr
integer :: irow
common /refactorc/
Type Attributes Name Initial
integer :: mc
integer :: mxmc
common /epsc/
Type Attributes Name Initial
real :: eps
real :: tol
real :: emin
common /pqc/
Type Attributes Name Initial
integer :: pc
integer :: qr
integer :: lmp
Call graph
updatese calls eptsol, aqsol
eptsol calls qprod, xlen, rtsol, aiscpri, eptsol0
aqsol calls rsol, scpr, aqsol0, qtprod, iscatter
rsol calls scpr
aqsol0 calls scpr, iscatter
eptsol0 calls aiscpri
qtprod calls scpr