update_L – filterSD
update_L Subroutine
561 statements
Source File
subroutine update_L(pp, qq, n, nm, a, la, lr, lc, li, mao, p, q, r, s, ws, mxws, d, sn, ifail)
Arguments
Type Intent Optional Attributes Name
real :: pp
real :: qq
integer :: n
integer :: nm
real :: a
integer :: la
integer :: lr
integer :: lc
integer :: li
integer :: mao
real :: p
real :: q
integer :: r
integer :: s
real :: ws
integer :: mxws
real :: d
real :: sn
integer :: ifail
Calls
Contents
Common Blocks
factorc refactorc iprintc epsc noutc
Common Blocks
common /factorc/
Type Attributes Name Initial
integer :: m1
integer :: nu
integer :: mp
integer :: mq
integer :: lastr
integer :: irow
common /refactorc/
Type Attributes Name Initial
integer :: nup
integer :: nfreq
common /iprintc/
Type Attributes Name Initial
integer :: iprint
common /epsc/
Type Attributes Name Initial
real :: eps
real :: tol
real :: emin
common /noutc/
Type Attributes Name Initial
integer :: nout
Call graph
update_l calls newslot, trim_, aiscpri2, iexch, aij, erase
newslot calls erase